management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8002
  servlet:
    context-path: /admin
spring:
  application:
    name: admin
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: 192.168.79.1:8848