# 与spring-boot-starter-actuator结合使用，监控服务
#
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8001
  servlet:
    context-path: /admin
#    context-path: /
spring:
  application:
    name: admin
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: 192.168.183.131:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      database: 0
      port: 6379
      host: 192.168.183.131
      password: dev123