# 与spring-boot-starter-actuator结合使用，监控服务
#
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 7000
#  servlet:
#    context-path: /
#    context-path: /
spring:
  application:
    name: oauth2
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  security:
    user:
      name: admin
      password: 123456