server:
  port: 10000
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway
  main:
    # 【spring-boot-starter-webflux】 和 springboot作为web项目启动必不可少的 【spring-boot-starter-web】 出现冲突。
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        # server-addr: 127.0.0.1:8848
        server-addr: 192.168.182.131:8848

