server:
  port: 10000
  servlet:
    context-path: /gateway
spring:
  application:
    name: gateway
  main:
    # 【spring-boot-starter-webflux】 和 springboot作为web项目启动必不可少的 【spring-boot-starter-web】 出现冲突。
    web-application-type: reactive
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        # server-addr: 127.0.0.1:8848
        server-addr: 192.168.182.131:8848
    gateway:
      #   # 相当于访问http://localhost:10000/gateway/authorization/echo/hello 转发到http://localhost:8000/authorization/echo/hello
      routes:
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/gateway/authorization/**
          filters:
            - RewritePath=/gateway/authorization/(?<remaining>.*), /authorization/$\{remaining}
#            - RewritePath=/gateway/authorization/(?<remaining>.*), /$\{remaining}
# 通过以上配置，当匹配到 /gateway/** 的请求时，Gateway 将会将请求转发到 http://example.com，并且去除了路径中的 /gateway/ 前缀。
        - id: system
          uri: lb://system
          predicates:
            - Path=/gateway/system/**
          filters:
            - RewritePath=/gateway/(?<remaining>.*), /$\{remaining}


  ##配置RSA的公钥访问地址
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8002/authorization/oauth/public-key'

  data:
    redis:
      database: 0
      port: 6379
      host: 192.168.182.131
      password: dev123

security:
  ignoreUrls:
    # 去请求认证时，可能还没有授权码，不拦截。
    - /gateway/authorization/**
    - /gateway/actuator/**
logging:
  level:
#    root: info
    root: debug